- hosts: all

  tasks:
    - name: Transfer the weedfs script
      copy: src=runfsserver.sh dest=/tmp/ mode=0777

    - name: Create file for master server logs
      ansible.builtin.file:
        path: /tmp/fsmasterrun.logs
        state: touch

    - name: Install seaweedfs and start master server
      ansible.builtin.shell: nohup /tmp/runfsserver.sh {{index . 0}} </dev/null >/tmp/fsmasterrun.logs 2>&1 &
      become: true