- hosts: all

  tasks:
    - name: Transfer the weedfs script
      copy: src=runfsserver.sh dest=/tmp/ mode=0777

    - name: Install seaweedfs and start master server
      ansible.builtin.shell: touch /tmp/fsmasterrun.logs; nohup /tmp/runfsserver.sh {{index . 0}} {{index . 1}} 
                              </dev/null >/tmp/fsmasterrun.logs 2>&1 &
      become: true