- hosts: all

  tasks:
    - name: Install etcd and start etcd server
      ansible.builtin.script: runetcd.sh
      become: true

    - name: Install seaweedfs and start master server
      ansible.builtin.script: runfsserver.sh {{index . 0}}
      become: true